#ifndef PROJECT_SELECT
#define PROJECT_SELECT

/**
 * Select the project to be compiled:
 *
 * 1) LED PWM OSCILATION 			(WITH CONTROL REGISTERS)
 * 2) DUAL LED PWM OSCILATION 		(WITH SDK)
 * 3) SERVO 180° ROTATION 			(WITH CUSTOM API)
 * 4) SERVO CONTROL WITH BUTTONS 	(WITH CUSTOM API)
 * 5) SERVO CONTROL WITH BUTTONS 	(WITH CUSTOM API W/ SERVO FUNCTIONS)
 * 6) FUNNY MELODY IN BUZZER		(WITH CUSTOM API)
 * 7) THE IMPERIAL MARCH			(WITH CUSTOM API W/ BUZZER FUNCTIONS)
 */
#define PROJECT 5

#endif
