#include <PIT_Select.h>
#if PIT_PROJECT == 1

#include "MKL25Z4.h"
#include <PIT_KL25Z.h>

/* INITIALIZES THE LEDS 01 AND 02 */
void LEDS_Init(void);

/* STARTS THE CHANNEL 0 OF PIT WITH 2s TO BLINK LED 01 */
void PIT0_Init(void);

/* STARTS THE CHANNEL 1 OF PIT WITH 8s TO BLINK LED 02 */
void PIT1_Init(void);

int main(void) {
	LEDS_Init();
	PIT0_Init();
	PIT1_Init();
	while(1);
}

void PIT_IRQHandler(void) {
	if(PIT->CHANNEL[0].TFLG & PIT_INTERRUPT_FLAG) {
		// CLEAR INTERRUPT FLAG
		PIT->CHANNEL[0].TFLG |= PIT_INTERRUPT_FLAG;

		// BLINK THE TWO LEDS
		LED_01_GPIO->PTOR |= LED_01_MASK;
	}
	else if(PIT->CHANNEL[1].TFLG & PIT_INTERRUPT_FLAG) {
		// CLEAR INTERRUPT FLAG
		PIT->CHANNEL[1].TFLG |= PIT_INTERRUPT_FLAG;

		// BLINK THE TWO LEDS
		LED_02_GPIO->PTOR |= LED_02_MASK;
	}
}

void LEDS_Init(void) {
	SIM->SCGC5 |= LED_01_CLOCK | LED_02_CLOCK;

	LED_01_PORT->PCR[LED_01] |= PORT_MUX_GPIO;
	LED_02_PORT->PCR[LED_02] |= PORT_MUX_GPIO;

	LED_01_GPIO->PDDR |= LED_01_MASK;
	LED_02_GPIO->PDDR |= LED_02_MASK;
}

void PIT0_Init(void) {
	// ENABLE CLOCK FOR PIT
	SIM->SCGC6 |= PIT_CLOCK;

	// ENABLE PIT TIMERS
	PIT->MCR &= PIT_TIMER_ENABLE;

	// SELECT 2s
	PIT->CHANNEL[0].LDVAL = PIT_PERIOD_2S;

	// ENABLE INTERRUPTS FOR PIT
	PIT->CHANNEL[0].TCTRL |= PIT_INTERRUPT_ENABLE;

	// ENABLE INTERRUPTS FOR PIT IN NVIC
	NVIC->ISER[0] |= NVIC_ENABLE_PIT;

	// START COUNT
	PIT->CHANNEL[0].TCTRL |= PIT_START_COUNT;
}

void PIT1_Init(void) {
	// ENABLE CLOCK FOR PIT
	SIM->SCGC6 |= PIT_CLOCK;

	// ENABLE PIT TIMERS
	PIT->MCR &= PIT_TIMER_ENABLE;

	// SELECT 8s
	PIT->CHANNEL[1].LDVAL = PIT_PERIOD_8S;

	// ENABLE INTERRUPTS FOR PIT
	PIT->CHANNEL[1].TCTRL |= PIT_INTERRUPT_ENABLE;

	// ENABLE INTERRUPTS FOR LPTMR0 IN NVIC
	NVIC->ISER[0] |= NVIC_ENABLE_PIT;

	// START COUNT
	PIT->CHANNEL[1].TCTRL |= PIT_START_COUNT;
}

#endif
