#include "LPTMR_Select.h"
#if LPTMR_PROJECT == 2

#include "MKL25Z4.h"
#include "LPTMR_KL25Z.h"

void LEDS_Init(void);
void LPTMR0_Init(void);

int main(void) {
	LEDS_Init();
	LPTMR0_Init();
	while(1);
}

void LPTMR0_IRQHandler(void) {
	// CLEAR INTERRUPT FLAG
	LPTMR0->CSR |= LPTMR0_INTERRUPT_FLAG;

	// BLINK THE TWO LEDS
	LED_01_GPIO->PTOR |= LED_01_MASK;
	LED_02_GPIO->PTOR |= LED_02_MASK;
}

void LEDS_Init(void) {
	SIM->SCGC5 |= LED_01_CLOCK | LED_02_CLOCK;

	LED_01_PORT->PCR[LED_01] |= PORT_MUX_GPIO;
	LED_02_PORT->PCR[LED_02] |= PORT_MUX_GPIO;

	LED_01_GPIO->PDDR |= LED_01_MASK;
	LED_02_GPIO->PDDR |= LED_02_MASK;
}

void LPTMR0_Init(void) {
	// ENABLE CLOCK FOR LPTMR0
	SIM->SCGC5 |= LPTMR0_CLOCK;

	// SELECT 1KHz CLOCK AND A /8 PRESCALER
	LPTMR0->PSR |= LPTMR0_CLOCK_LPO | LPTMR0_PRESCALER_8;

	// T = (1/(1KHz/8)) = 8ms
	// CMR = 8s/8ms = 1000 COUNTS
	LPTMR0->CMR = 999;

	// ENABLE INTERRUPTS FOR LPTMR0 AND ENABLE IT
	LPTMR0->CSR |= LPTMR0_TIMER_ENABLE | LPTMR0_INTERRUPT_ENABLE;

	// ENABLE INTERRUPTS FOR LPTMR0 IN NVIC
	NVIC->ISER[0] |= NVIC_ENABLE_LPTMR0;
}

#endif
