#ifndef LPTMR_SELECT_H
#define LPTMR_SELECT_H

/*
 * SELECT PROJECT WITH LPTMR:
 * 1 = BLINK LED WITH 1s DELAY
 * 2 = BLINK LED WITH 8s DELAY
 * 3 = BLINK TWO LEDs WITH 1s AND 8s DELAY
 * 4 = BLINK LED WITH 1s DELAY WITH SDK
 * 5 = BLINK LED WITH 8s DELAY WITH SDK
 */
#define LPTMR_PROJECT 1

#endif
