#ifndef TPM_SELECT_H
#define TPM_SELECT_H

/*
 * SELECT PROJECT WITH LPTMR:
 * 1 = BLINK LED WITH 1s DELAY
 * 2 = BLINK LED WITH 8s DELAY
 * 3 = BLINK TWO LEDs WITH 2s AND 8s DELAY
 * 4 = BLINK TWO LEDs WITH 2s AND 8s DELAY WITH SDK
 */
#define TPM_PROJECT 4

#endif
